# ln -s ~/dotfiles/special/zsh/zshenv ~/.zshenv

# Startup scripts
#
#   1. Always:      ~/.zshenv
#   2. Login:       ~/.config/zsh/.zprofile
#   3. Interactive: ~/.config/zsh/.zshrc
#   4. Prezto:      ~/.config/zsh/.zpreztorc
#   5. Login:       ~/.config/zsh/.zlogin
#
# Login shell = outermost shell. Will be true e.g. for shells started from tmux.
#   [[ -o interactive ]] && echo 'Interactive' || echo 'Not interactive'
#
# Interactive shell = hooked up to TTY
#   [[ -o login ]] && echo 'Login' || echo 'Not login'

export ZDOTDIR=$HOME/.config/zsh
